replace broken action

diff --git a/.github/workflows/cron.yaml b/.github/workflows/cron.yaml
--- a/.github/workflows/cron.yaml
+++ b/.github/workflows/cron.yaml
@@ -24,14 +24,13 @@ jobs:
     outputs:
       tag: ${{ steps.check-tag.outputs.tag }}
     steps:
+    - uses : actions/checkout@v4
     - id: check-tag
       env:
         tag: ${{ needs.check-versions.outputs.tag }}
-      uses: tyriis/docker-image-tag-exists@v2.0.0
-      with:
-        registry: docker.io
-        respository: mmta/alpine-glibc
-        tag: ${{ env.tag }}
+      run: |
+        docker manifest inspect mmta/alpine-glibc:$tag || { [ $? -eq 1 ] && echo "tag=not found" >> $GITHUB_OUTPUT && exit 0; }
+        echo "tag=found" >> $GITHUB_OUTPUT
   build:
     runs-on: ubuntu-latest
     needs:
